# Generated by Django 4.2 on 2025-05-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fechaMensaje',
            field=models.DateTimeField(),
        ),
    ]
